# Everforest Light (Soft) by sainnhe
# https://github.com/sainnhe/everforest

background  #F3EAD3
foreground  #5C6A72

cursor                #5C6A72

selection_foreground  #5C6A72
selection_background  #DDD8BE

color0  #EAE4CA
color8  #A6B0A0

# red
color1                #F85552
# light red
color9                #F85552

# green
color2                #8DA101
# light green
color10               #8DA101

# yellow
color3                #DFA000
# light yellow
color11               #DFA000

# blue
color4                #3A94C5
# light blue
color12               #3A94C5

# magenta
color5                #DF69BA
# light magenta
color13               #DF69BA

# cyan
color6                #35A77C
# light cyan
color14               #35A77C

# light gray
color7                #939F91
# dark gray
color15               #829181
